const mongoose = require('mongoose');

const BarcodeSchema = new mongoose.Schema({
    code: { type: String, required: true, unique: true },
    url: { type: String },
    creator: { type: String },
    created_t: { type: Number },
    created_datetime: { type: Date },
    last_modified_t: { type: Number },
    last_modified_datetime: { type: Date },
    product_name: { type: String },
    generic_name: { type: String },
    quantity: { type: String },
    packaging: { type: String },
    packaging_tags: [{ type: String }],
    brands: { type: String },
    brands_tags: [{ type: String }],
    categories: { type: String },
    categories_tags: [{ type: String }],
    origins: { type: String },
    origins_tags: [{ type: String }],
    labels: { type: String },
    labels_tags: [{ type: String }],
    emb_codes: { type: String },
    emb_codes_tags: [{ type: String }],
    cities_tags: [{ type: String }],
    purchase_places: { type: String },
    stores: { type: String },
    countries: { type: String },
    countries_tags: [{ type: String }],
    ingredients_text: { type: String },
    traces: { type: String },
    traces_tags: [{ type: String }],
    serving_size: { type: String },
    no_nutriments: { type: String },
    additives_n: { type: Number },
    additives_tags: [{ type: String }],
    ingredients_from_palm_oil_n: { type: Number },
    ingredients_from_palm_oil_tags: [{ type: String }],
    ingredients_that_may_be_from_palm_oil_n: { type: Number },
    ingredients_that_may_be_from_palm_oil_tags: [{ type: String }],
    nutrition_grade_fr: { type: String },
    main_category: { type: String },
    main_category_fr: { type: String },
    image_url: { type: String },
    image_small_url: { type: String },
    energy_100g: { type: Number },
    energy_kj_100g: { type: Number },
    energy_kcal_100g: { type: Number },
    proteins_100g: { type: Number },
    carbohydrates_100g: { type: Number },
    sugars_100g: { type: Number },
    fat_100g: { type: Number },
    saturated_fat_100g: { type: Number },
    fiber_100g: { type: Number },
    sodium_100g: { type: Number },
    vitamin_c_100g: { type: Number }
});

module.exports = mongoose.model('Barcode', BarcodeSchema);